### ISSUE TITLE
Use liveness rather then sleep in docker test

### ISSUE THREAD

**Issue by casz** [jdalrymple/node-gitlab#132]
Use liveness health check instead of using a sleep 240, should speed up the waiting part.
https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html
https://docs.gitlab.com/ee/administration/monitoring/ip_whitelist.html

Health check is possible via ip_whitelist
https://gitlab.com/-/liveness

**Comment by jdalrymple** [comment]
Such a better idea thank you 🙏

**Comment by jdalrymple** [comment]
Will be in next release

**Comment by jdalrymple** [comment]
liveliness and readiness are still too short :( they avg about 100ms, but the actual service doesnt get up and moving until maybe 200ms

**Comment by casz** [comment]
see https://github.com/jdalrymple/node-gitlab/commit/f4f1aeefd1d3bb2d400dbc12cc570278c45ba63e#commitcomment-29809139

**Comment by jdalrymple** [comment]
So even looking at the status', it still isnt completely up:

Here is the first response to return back 200. Notice how all the status' are OK
{"db_check":{"status":"ok"},"redis_check":{"status":"ok"},"cache_check":{"status":"ok"},"queues_check":{"status":"ok"},"shared_state_check":{"status":"ok"},"fs_shards_check":{"status":"ok","labels":{"shard":"default"}},"gitaly_check":{"status":"ok","labels":{"shard":"default"}}

But then testing that everything is complete

    docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"'

Returns ''

Hmm maybe its because of my docker-entrypoint file.

In that file it runs the gitlab init, waits for 30 seconds and then exports the env vars. So when i test for readiness, its returning true after that init, but the exports havent happened yet.

Hmm, need to think of a way around that.

**Comment by jdalrymple** [comment]
Closing this for now, If we can find a better way to do this in the future, ill reopen
