### ISSUE TITLE
Using XMLHttpRequests results in broken 'fs' dependency

### ISSUE THREAD

**Issue by icosamuel** [jdalrymple/node-gitlab#98]
I'm trying to use your api client [in the browser](https://github.com/jdalrymple/node-gitlab/issues/56). So far i've been unable to build my SPA because of a dependency thats not available in the browser (fs). 

```
$ npm install --save fs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ fs@0.0.1-security
updated 1 package in 17.193s
```

```
This dependency was not found:

* fs in ./node_modules/gitlab/dist/latest/services/Projects.js, ./node_modules/request/lib/har.js

To install it, you can run: npm install --save fs
```
It seems ratter normal that fs cannot be used in the browser [[1]](https://github.com/nodejs/help/issues/547) [[2]](https://stackoverflow.com/questions/50370975/npm-stream-player-causing-fs-dependency-not-found).

What can I do to work around this?

If no workarounds are possible, Is there anyone else encountering the same issue and should we try to make a browser-friendly version?

**Comment by jdalrymple** [comment]
Wait the standard node fs library isn't available but the other ones are ? :P something about that is off

**Comment by jdalrymple** [comment]
Hmm. Lemme look

**Comment by jdalrymple** [comment]
It's only used for the upload function, to read in files. Could switch it with another library but I'm not sure that would solve your problem

**Comment by icosamuel** [comment]
There is also a reference in the `request` module that acts as a dependency to this project. I'm not sure either how to go about solving this

**Comment by jdalrymple** [comment]
Me neither :s I'll do some research tonight

**Comment by icosamuel** [comment]
So I've spent a couple of hours migrating the http-request lib to Axios. In the process, I eliminated all dependencies to `fs`. So I guess this would count as option 1, but not easily mergable.

I've forked the project to meet my needs, but I'd love for some ideas on how to contribute to your project. Here it is: https://github.com/icosamuel/node-gitlab/pull/1

**Comment by jdalrymple** [comment]
@Mr-Wallet any suggestions?

**Comment by Mr-Wallet** [comment]
The best option would be to abstract the request layer so that clients could inject their own dependency. Basically `BaseService` would take in a `requester` that must implement certain methods, and the interface would be basically the same as the `request` library, and if the client wants to use something other than `request` (e.g. `xhr`, or something that doesn't rely on `fs`), it would be the client's responsibility to write the adapter. This is what I probably _ought_ to have done when adding XHR support to this library but it would have taken longer.

**Comment by icosamuel** [comment]
Not sure how that would be done, but there is also one call (upload i think) in `services/Projects.js` that requires the use of `fs`.

If I may suggest, Axios is getting an incredible amount of love on github. It works for node and the browser and has promises included. Do you think it is viable option to consider migrating?

**Comment by Mr-Wallet** [comment]
That may be a superior default; just remember that today's Axios is tomorrow's dead project. I would recommend building the abstraction layer now.

My team uses node-gitlab for a desktop application that can't update at the drop of a hat and which hundreds of thousands of people rely on. Axios is moving a little fast (still has a mediocre stars-to-issues ratio, breaking change every couple months) and while it's been around long enough that I'm sure most of the worst kinks have been worked out, I personally would feel a lot safer with a mechanism to drop Axios if anything goes wrong in my use case, without having to wrestle a solution into a personal fork the way we had to do with this project's predecessor or the way @icosamuel just had to do.

**Comment by jdalrymple** [comment]
Lol I agree. I'll work on making an abstraction layer for the next major release but will keep request as a default for simplicity

**Comment by jdalrymple** [comment]
I've started working on this. I've removed the dependency internally and am working on the abstraction of the request module. There are a couple things im unsure of how to solve:

1. Consistency of the libraries. Right now their is a helper to simplify the requests. This helper assumes the request library follows a certain API. As we've seen with xhr and axios (more so the former than the latter) there is not standard API for these libraries, which usually requires us to write a wrapper (as seem with the XMLHTTPRequester file, to maintain the same API. Is this something that would have to be done for every request module the user would want to use? Or is there another way around this?

2. How to handle streams AND promises. Right now we use request for the stream and request-promise for everything else. How would this be handled by other libraries the user decided to use?

Thanks for the input :)

**Comment by Mr-Wallet** [comment]
Well, here's my personal take:

#1 Is not really solvable - if you want it to work for _everything,_ you must provide an API. The API could coincidentally match up with one existing library, but that's as far as you can get.

For #2: nothing is stopping people from importing as many modules as they like in their adapter. The abstraction could handle both streams and promises, but the underlying implementation can use more than one module. I don't see any real hardship on the developer since it's a simple `if` check for the `stream` option.

**Comment by jdalrymple** [comment]
:joy: #documentation sounds good! Will set up a prototype in a week or so! Woo progress

**Comment by jdalrymple** [comment]
It has been suggested that one of fetch libraries is both node and browser compatible. Thoughts?

**Comment by Mr-Wallet** [comment]
I'm not totally up to speed on that discussion but the main reason we needed XMLHttpRequest (XHR) is that we have a lot of users in professional environments with badly-formed certs and peculiar hipster proxies, neither of which they're totally in control of. The thing is, Chrome and all Electron apps can all use the same settings for certs and proxies, and using XHR in Electron causes it to handle all of that. As a developer we don't need to figure out all the ways that certs/proxies can possibly work and figure out how to handle them, we can just rely 100% on the Chromium implementation. For our customers this means: "Can you access your GitLab server's website from your machine on Chrome without Chrome giving you a certificate error? Yes? Then you're already done before you even installed GitKraken, our API integration will work." This is a huge boon for us as developers, and for our customers as people who don't know anything about how certs or proxies work and have created a configuration abomination that follows no specs and only _barely, coincidentally_ works with their current softwares.

So my basic perspective, as an Electron developer, is "I absolutely require this module, at the bottom of all the code, to go through the browser's XMLHttpRequest". If I have no recourse for that then I have absolutely no choice but to do what I did for this project's predecessor, which is to maintain our own fork. That's my team's perspective, and I recognize that it's selfish. But for the moment this is the only proper Node module for v4 of the API and so it regrettably must try to be all things to all people. If that fetch library is friendly to XHR use then I'm all for it, but if not then the ability to inject my own "requester" would still be critical.

**Comment by jdalrymple** [comment]
So a requirement for the changes is either 1. A library that is xhr friendly 
2. Full ability to substitute the request library 

:)

**Comment by jdalrymple** [comment]
Ive found these two:

https://github.com/serviejs/popsicle 
https://www.npmjs.com/package/xhr-request

Still looking to ensure they have all the necessary functionality

ie. 
    headers,
    body,
    qs,
    formData,
    resolveWithFullResponse
   authorization etc

**Comment by jdalrymple** [comment]
We could also internalize this https://github.com/naugtur/xhr

**Comment by jdalrymple** [comment]
@Mr-Wallet What would be the best way for me to test that it works properly in the browser. It would be a good test to setup in travis for the future.

**Comment by icosamuel** [comment]
@jdalrymple May I suggest testing a few Gitlab endpoints through a popular front-end packager such as `webpack` or `browserify`? If I remember correctly, the problem was with libraries that are exclusive to node such as `fs`.

**Comment by jdalrymple** [comment]
true, @Mr-Wallet with electron are you using webpack/browserify to package this node package? Creating a test case to ensure that any library changes i make don't mess it up for browser use cases would be very helpful

**Comment by icosamuel** [comment]
If I understand correctly, you would have to run your code in a browser instead of node. Maybe some headless browser testing framework like `phantomjs` would help?

**Comment by jdalrymple** [comment]
Yup! I want to write a test to ensure browser compatibility is maintained. So that would include running a test script that used webpack/browserify, and a headless browser situation i think. Any guidance here would be appreciated. 

At least this way when we do update the request libraries, it wont break for anyone using it within the browser.

**Comment by Mr-Wallet** [comment]
I also don't have much expertise in this area, so I'm going to ask my co-worker @implausible, who has done more research on this kind of testing, to chime in.

**Comment by implausible** [comment]
I think you're on track with webpack/browserify + a headless browser. I just recently did this for one of our websites. What I ended up doing was implementing a custom reporter (socket client) in mocha which forwarded test data over a socket back to a test driver (socket server). The socket server pretty much just spits out whatever the results of the tests are the same way that the usual mocha reporter does it and also exits with an error code if the socket receives failures. I chose this implementation strategy, because if a test were to freeze the headless browser, it would be nice to see the last output from the test before travis times out the test.

In the past I found PhantomJS to be pretty terribad with a lot of gotchas as far as browser standards go, so I usually stick to real browsers in headless mode if I can. It looks like Travis has support for headless chrome https://docs.travis-ci.com/user/chrome#headless-mode. It also looks like Jest can be configured to use a custom test reporter https://jestjs.io/docs/en/configuration.

If you don't want to use the socket system, you will still need to figure out a way to have the headless browser communicate back to the running process that the tests completed and what the results were. You should be able to output whatever is on the dom though, so you could theoretically have your customer reporter write plain text to the dom and print that out at the test exit.

Hope this helps!

**Comment by jdalrymple** [comment]
released in the next tag on npm!

**Comment by westurner** [comment]
I've tried 4.2.7 (fs, net, tls), 4.5.1 (fs, net, tls), and next (5.0.0-rc.10) (#282 ``"Request with GET/HEAD method cannot have body. at Ky._fetch"``) . Any idea which version should work in Chrome 73?

**Comment by westurner** [comment]
4.5 works when I add this to my webpack config: as described here https://github.com/peaksandpies/universal-analytics/issues/58#issuecomment-279485637 :

```
node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
```

**Comment by jdalrymple** [comment]
@westurner sorry about that! Still working on fixing this in the new version. Just been running low on time recently :(
